@startuml OcenjevanjeArhiviranegaPredlogaAlt

hide footbox

skinparam backgroundcolor white
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

title "Ocenjevanje arhiviranega predloga - alternativni tok"

actor "Prijavljen uporabnik" AS U <<actor>>

participant "Predlogi" as Predlogi <<view>>
participant "Krmilnik upravljanja predlogov" as Krmilnik <<controller>>
participant "Predlog" as  PredlogModel <<model>>


U -> Predlogi: prikaziArhiv()
activate Predlogi

Predlogi -> Krmilnik: vrniPredloge()
activate Krmilnik

Krmilnik -> PredlogModel: vrniPredloge()
activate PredlogModel

PredlogModel -[dotted]> Krmilnik: seznamPredlogov
deactivate PredlogModel

Krmilnik -[dotted]> Predlogi: seznamPredlogov
deactivate Krmilnik


deactivate Krmilnik

U -> Predlogi: vnos ocene pri predlogu
Predlogi -> Krmilnik: posodobiPredlog()
activate Krmilnik
Krmilnik -> PredlogModel: posodobiPredlog()
activate PredlogModel
PredlogModel -[dotted]> Krmilnik: posodobljenPredlog
deactivate PredlogModel
Krmilnik -[dotted]> Predlogi: posodobljenPredlog
deactivate Krmilnik

Predlogi -> Predlogi: posodobiStran()
Predlogi -> Predlogi: prikaziSporocilo()


@enduml
