@startuml PrijavaIzjemni2

hide footbox

skinparam backgroundcolor white
skinparam defaultTextAlignment center
skinparam actorBorderColor black
skinparam actorBackgroundColor white
skinparam arrowColor black  
skinparam sequenceLifeLineBorderColor #5FB8EC
skinparam sequenceParticipantBorderColor #5FB8EC
skinparam sequenceParticipantBackgroundColor white

title "Prijava - izjemni tok 2"

actor "Neprijavljen uporabnik" AS U1 <<actor>>

participant "Prijava" as R5 <<view>>
participant "Krmilnik upravljanja računov" as R2 <<controller>>
participant "Uporabnik" as R4 <<model>>

'activate U1
activate R5

'R2 -> R5: neprijavljenDostop()


U1 -> R5: pricniPrijavo()
'R5 -> R5: prikaziObrazecPrijava()

U1 -> R5: izpolniObrazec()
U1 -> R5: potrdiPrijavo()

activate R2

R5 -> R2: prijaviUporabnika()
R2 -> R2: poljaPrijavaIzpolnjena()

activate R4

R2 -> R4: vrniPodatkeUporabnika()
R4 -[dotted]> R2: podatkiUporabnika

deactivate R4

R2 -> R2: preveriBlokiranost()
R2 -> R2: preveriPodatkePrijava()
'R2 -> R2: nastaviSejo()


'R2 -[dotted]> R5: prijavaUspesna()
'R5 -> R2: vrniPodatkeUporabnika()
'R2 -[dotted]> R5: podatkiUporabnika()

'activate R4
'R2 -> R4: vrniPodatkeUporabnika()
'R4 -[dotted]> R2: podatkiUporabnika()
'deactivate R4

R2 -[dotted]> R5: neveljavnoGeslo
R5 -> R5: prikaziObvestiloNeveljavnoGeslo()


@enduml
