export const OBCINE = [
	{name: "Ajdovščina"},
	{name: "Ankaran"},
	{name: "Apače"},
	{name: "Beltinci"},
	{name: "Benedikt"},
	{name: "Bistrica ob Sotli"},
	{name: "Bled"},
	{name: "Bloke"},
	{name: "Bohinj"},
	{name: "Borovnica"},
	{name: "Bovec"},
	{name: "Braslovče"},
	{name: "Brda"},
	{name: "Brezovica"},
	{name: "Brežice"},
	{name: "Cankova"},
	{name: "Celje"},
	{name: "Cerklje na Gorenjskem"},
	{name: "Cerknica"},
	{name: "Cerkno"},
	{name: "Cerkvenjak"},
	{name: "Cirkulane"},
	{name: "Črenšovci"},
	{name: "Črna na Koroškem"},
	{name: "Črnomelj"},
	{name: "Destrnik"},
	{name: "Divača"},
	{name: "Dobje"},
	{name: "Dobrepolje"},
	{name: "Dobrna"},
	{name: "Dobrova - Polhov Gradec"},
	{name: "Dobrovnik"},
	{name: "Dol pri Ljubljani"},
	{name: "Dolenjske Toplice"},
	{name: "Domžale"},
	{name: "Dornava"},
	{name: "Dravograd"},
	{name: "Duplek"},
	{name: "Gorenja vas - Poljane"},
	{name: "Gorišnica"},
	{name: "Gorje"},
	{name: "Gornja Radgona"},
	{name: "Gornji Grad"},
	{name: "Gornji Petrovci"},
	{name: "Grad"},
	{name: "Grosuplje"},
	{name: "Hajdina"},
	{name: "Hoče - Slivnica"},
	{name: "Hodoš"},
	{name: "Horjul"},
	{name: "Hrastnik"},
	{name: "Hrpelje - Kozina"},
	{name: "Idrija"},
	{name: "Ig"},
	{name: "Ilirska Bistrica"},
	{name: "Ivančna Gorica"},
	{name: "Izola"},
	{name: "Jesenice"},
	{name: "Jezersko"},
	{name: "Juršinci"},
	{name: "Kamnik"},
	{name: "Kanal ob Soči"},
	{name: "Kidričevo"},
	{name: "Kobarid"},
	{name: "Kobilje"},
	{name: "Kočevje"},
	{name: "Komen"},
	{name: "Komenda"},
	{name: "Koper"},
	{name: "Kostanjevica na Krki"},
	{name: "Kostel"},
	{name: "Kozje"},
	{name: "Kranj"},
	{name: "Kranjska Gora"},
	{name: "Križevci"},
	{name: "Krško"},
	{name: "Kungota"},
	{name: "Kuzma"},
	{name: "Laško"},
	{name: "Lenart"},
	{name: "Lendava"},
	{name: "Litija"},
	{name: "Ljubljana"},
	{name: "Ljubno"},
	{name: "Ljutomer"},
	{name: "Log - Dragomer"},
	{name: "Logatec"},
	{name: "Loška dolina"},
	{name: "Loški Potok"},
	{name: "Lovrenc na Pohorju"},
	{name: "Luče"},
	{name: "Lukovica"},
	{name: "Majšperk"},
	{name: "Makole"},
	{name: "Maribor"},
	{name: "Markovci"},
	{name: "Medvode"},
	{name: "Mengeš"},
	{name: "Metlika"},
	{name: "Mežica"},
	{name: "Miklavž na Dravskem polju"},
	{name: "Miren - Kostanjevica"},
	{name: "Mirna"},
	{name: "Mirna Peč"},
	{name: "Mislinja"},
	{name: "Mokronog - Trebelno"},
	{name: "Moravče"},
	{name: "Moravske Toplice"},
	{name: "Mozirje"},
	{name: "Murska Sobota"},
	{name: "Muta"},
	{name: "Naklo"},
	{name: "Nazarje"},
	{name: "Nova Gorica"},
	{name: "Novo mesto"},
	{name: "Odranci"},
	{name: "Oplotnica"},
	{name: "Ormož"},
	{name: "Osilnica"},
	{name: "Pesnica"},
	{name: "Piran"},
	{name: "Pivka"},
	{name: "Podčetrtek"},
	{name: "Podlehnik"},
	{name: "Podvelka"},
	{name: "Poljčane"},
	{name: "Polzela"},
	{name: "Postojna"},
	{name: "Prebold"},
	{name: "Preddvor"},
	{name: "Prevalje"},
	{name: "Ptuj"},
	{name: "Puconci"},
	{name: "Rače - Fram"},
	{name: "Radeče"},
	{name: "Radenci"},
	{name: "Radlje ob Dravi"},
	{name: "Radovljica"},
	{name: "Ravne na Koroškem"},
	{name: "Razkrižje"},
	{name: "Rečica ob Savinji"},
	{name: "Renče - Vogrsko"},
	{name: "Ribnica"},
	{name: "Ribnica na Pohorju"},
	{name: "Rogaška Slatina"},
	{name: "Rogašovci"},
	{name: "Rogatec"},
	{name: "Ruše"},
	{name: "Selnica ob Dravi"},
	{name: "Semič"},
	{name: "Sevnica"},
	{name: "Sežana"},
	{name: "Slovenj Gradec"},
	{name: "Slovenska Bistrica"},
	{name: "Slovenske Konjice"},
	{name: "Sodražica"},
	{name: "Solčava"},
	{name: "Središče ob Dravi"},
	{name: "Starše"},
	{name: "Straža"},
	{name: "Sveta Ana"},
	{name: "Sveta Trojica v Slovenskih goricah"},
	{name: "Sveti Andraž v Slovenskih goricah"},
	{name: "Sveti Jurij ob Ščavnici"},
	{name: "Sveti Jurij v Slovenskih goricah"},
	{name: "Sveti Tomaž"},
	{name: "Šalovci"},
	{name: "Šempeter - Vrtojba"},
	{name: "Šenčur"},
	{name: "Šentilj"},
	{name: "Šentjernej"},
	{name: "Šentjur"},
	{name: "Šentrupert"},
	{name: "Škocjan"},
	{name: "Škofja Loka"},
	{name: "Škofljica"},
	{name: "Šmarje pri Jelšah"},
	{name: "Šmarješke Toplice"},
	{name: "Šmartno pri Litiji"},
	{name: "Šmartno ob Paki"},
	{name: "Šoštanj"},
	{name: "Štore"},
	{name: "Tabor"},
	{name: "Tišina"},
	{name: "Tolmin"},
	{name: "Trbovlje"},
	{name: "Trebnje"},
	{name: "Trnovska vas"},
	{name: "Trzin"},
	{name: "Tržič"},
	{name: "Turnišče"},
	{name: "Velenje"},
	{name: "Velika Polana"},
	{name: "Velike Lašče"},
	{name: "Veržej"},
	{name: "Videm"},
	{name: "Vipava"},
	{name: "Vitanje"},
	{name: "Vodice"},
	{name: "Vojnik"},
	{name: "Vransko"},
	{name: "Vrhnika"},
	{name: "Vuzenica"},
	{name: "Zagorje ob Savi"},
	{name: "Zavrč"},
	{name: "Zreče"},
	{name: "Žalec"},
	{name: "Železniki"},
	{name: "Žetale"},
	{name: "Žiri"},
	{name: "Žirovnica"},
	{name: "Žužemberk"},
]
