name: Continuous integration

on:
  push:
    branches:
      - test
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        node-verzija:
          - 16.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Uporabi Node.js ${{ matrix.node-verzija }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-verzija }}
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - run: |-
          cd src/
          echo '${{ secrets.GCP_CREDENTIALS }}' >> ./config/service_account.json
          echo 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}' >> ./.env
          yarn install
          yarn dev &
          yarn test
